function  [changetype,median_no_of_change] = get_median_of_node_change_per_commit(obj,nodetype)
%GET_MEDIAN_OF_NODE_CHANGE_PER_COMMIT Summary of this function goes here
%   Detailed explanation goes here
median_query = ['SELECT distinct change_type,'...
                    'AVG('...
                    ' CASE counter%2'... 
                    ' WHEN 0 THEN CASE WHEN rn in (counter/2, counter /2 +1) THEN totalCount END '...
                    ' WHEN 1 THEN CASE WHEN rn = counter/ 2 + 1 THEN totalCount END '...
                    ' END)'... 
                    ' OVER (partition by change_type) median'...
                    ' FROM ('...
                    ' SELECT *, row_number() OVER (PARTITION  BY change_type order by totalCount) rn,'...
                    ' count(*) over (PARTITION by change_type) counter'...
                    ' FROM ('...
                    ' SELECT'... 
                    ' Before_Project_Folder, After_Project_Folder,'...      
                    ' CASE'...  
                    ' WHEN is_deleted > 0 THEN "Deleted"'...  
                    ' WHEN is_added > 0 THEN "Added"  '...
                    ' WHEN is_modified > 0 THEN "Modified"  '...
                    ' WHEN is_renamed > 0 THEN "Renamed"'...  
                    ' END AS change_type,totalCount  '...
                    ' FROM (	'... 
                    ' SELECT Before_Project_Folder, After_Project_Folder, is_deleted, is_added, is_modified, is_renamed, count(*) as totalCount'... 
                    ' FROM ' char(obj.table_name) ...
                    ' WHERE( is_deleted = 1 or is_added = 1 or is_modified = 1 or is_renamed = 1 ) '...
                    ' AND node_type = "' nodetype '"'...
                    ' GROUP BY Before_Project_Folder, After_Project_Folder, is_deleted, is_added, is_modified, is_renamed) '...
                    ' ORDER BY change_type, totalCount)'...
                    ' )'...
                    ' ORDER BY median DESC'];
         result = fetch(obj.conn, median_query);
         [rows,~] = size(result);
         median_no_of_change = zeros(1,min(4,rows));
         changetype = cell(1,min(4,rows));
         %Added, deleted, modified and renamed
        for r = 1:min(4,rows)
            median_no_of_change(1,r) = result{r,2};  
            changetype{1,r} = [nodetype ' ' result{r,1}];
        end
end

